export const OPERATION_IDS = {
  APPLICATIONS: {
    GET_APPLICATIONS: "GET_APPLICATIONS",
  },
  AUTHORIZATION: {
    CHECK_AUTHORIZATION: "CHECK_AUTHORIZATION",
  },
  CARDS: {
    GET_CARDS: "GET_CARDS",
    CREATE_CARD: "CREATE_CARD",
  },
  VENDOR_DASHBOARD: {
    GET_OTP: "GET_OTP",
  },
  INVOICE: {
    INVOICE: "INVOICE",
  },
  MESSAGES: {
    GET_MESSAGES: "GET_MESSAGES",
    SEND_MESSAGES: "SEND_MESSAGES",
  },
  MOBILE_VERSION: {
    GET_MOBILE_VERSION: "GET_MOBILE_VERSION",
  },
  SCANS: {
    GET_SCANS: "GET_SCANS",
  },
  USER:{
    GET_CURRENT_USER:'GET_CURRENT_USER'
  }
};
