export const OPERATION_IDS = {
  APPLICATIONS: {
    GET_APPLICATIONS: "GET_APPLICATIONS",
  },
  AUTHORIZATION: {
    CHECK_AUTHORIZATION: "CHECK_AUTHORIZATION",
  },
  CARDS: {
    GET_CARDS: "GET_CARDS",
    CREATE_CARD: "CREATE_CARD",
  },
  VENDOR_DASHBOARD: {
    GET_OTP: "GET_OTP",
  },
  INVOICE: {
    INVOICE: "INVOICE",
  },
  MESSAGES: {
    GET_MESSAGES: "GET_MESSAGES",
    SEND_MESSAGES: "SEND_MESSAGES",
    DELETE_MESSAGES: "DELETE_MESSAGES",
  },
  MOBILE_VERSION: {
    GET_MOBILE_VERSION: "GET_MOBILE_VERSION",
  },
  SCANS: {
    GET_SCANS: "GET_SCANS",
  },
  USER: {
    GET_CURRENT_USER: "GET_CURRENT_USER",
    DELETE_USER: "DELETE_USER",
    GET_ALL_USERS: "GET_ALL_USERS",
    PATCH_USER: "PATCH_USER",
    UPDATE_USER: "UPDATE_USER",
  },
  LEADS: {
    CREATE_LEAD: "CREATE_LEAD",
  },
  NOTIFICATIONS: {
    GET_NOTIFICATIONS: "GET_NOTIFICATIONS",
    CREATE_NOTIFICATION: "CREATE_NOTIFICATION",
    UPDATE_NOTIFICATION: "UPDATE_NOTIFICATION",
    DELETE_NOTIFICATION: "DELETE_NOTIFICATION",
    MARK_ALL_READ: "MARK_ALL_READ",
    GET_UNREAD_COUNT: "GET_UNREAD_COUNT",
  },
  LMS_USERS: {
    USER_MANAGEMENT: "USER_MANAGEMENT",
  },
};
