export const HTTP_RESOURCES = {
  OTP: "otp",
  DASHBOARD: "dashboard",
  APPLICATIONS: "applications",
  SCANS: "scans",
  INVOICES: "invoices",
  AUTHORIZATION: {
    CHECK_AUTHORIZATION: "checkAuthorization",
  },
  GET_CARDS: "getCards",
  CREATE_CARD: "createCard",
  MESSAGES: "usermessages",
  FAQS: "faqs",
  BLOGS: "blogs",
  GET_UPLOAD_URL: "getUploadUrl",
  MOBILE_VERSION: "mobileVersion",
  ENQUIRY: "enquiry",
  ORGANIZATION: {
    GET_ORG_INFO: "getOrgInfo",
  },
  WELCOME_MESSAGE: "welcomeMessage",
  PARTNER_REGISTRATION: "partnerRegistration",
  INSIGHTS: "insights",
  CREATE_LEAD: "sbi-lead",
  USER: "user",
  USERS: "users",
  NOTIFICATIONS: {
    GET_NOTIFICATIONS: "notifications",
    CREATE_NOTIFICATION: "notifications",
    UPDATE_NOTIFICATION: "notifications/:id",
    DELETE_NOTIFICATION: "notifications/:id",
    MARK_ALL_READ: "notifications/mark-all-read",
    GET_UNREAD_COUNT: "notifications/unread-count",
  },
  LMS_USERS: "lmsUsers",
};
