export const env = {
    SMS_API_KEY: process.env.SMS_API_KEY,
    SMS_API_URL: process.env.SMS_API_URL,
    SMS_WELCOME_TEMPLATE_ID: process.env.SMS_WELCOME_TEMPLATE_ID,
    SMS_OTP_TEMPLATE_ID: process.env.SMS_OTP_TEMPLATE_ID,
    SMS_VENDOR_TEMPLATE_ID: process.env.SMS_VENDOR_TEMPLATE_ID,
    SMS_TATA_TEL_USERNAME: process.env.SMS_TATA_TEL_USERNAME,
    SMS_TATA_TEL_PASSWORD: process.env.SMS_TATA_TEL_PASSWORD,
    SMS_SENDER_ID: process.env.SMS_SENDER_ID,
    SMS_TATA_TEL_PE_ID: process.env.SMS_TATA_TEL_PE_ID,
    MONGO_DB_URL: process.env.MONGO_DB_URL,
    JWT_SECRET: process.env.JWT_SECRET,
    JWT_EXPIRY: process.env.JWT_EXPIRY,
}