// OTP expiration time in milliseconds
export const OTP_EXPIRATION_TIME = 24 * 60 * 60 * 1000; // 24 hours
export const WELCOME_MESSAGE_EXPIRATION_TIME = 24 * 60 * 60 * 1000;

export enum OTP_RESPONSE_CODES {
  OTP_SENT = "OTP_SENT",
  OTP_VERIFIED = "OTP_VERIFIED",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_NOT_SENT = "OTP_NOT_SENT",
  OTP_NOT_VERIFIED = "OTP_NOT_VERIFIED",
  OTP_ALREADY_VERIFIED = "OTP_ALREADY_VERIFIED",
  OTP_NOT_FOUND = "OTP_NOT_FOUND",
  OTP_ERROR = "OTP_ERROR",
  OTP_NOT_EXPIRED = "OTP_NOT_EXPIRED",
  INVALID_OTP_CODE = "INVALID_OTP_CODE",
}
